apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    app: backend
    tier: backend
    project: expense
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
    spec:
      containers:
      - name: nginx
        image: soumya081693/backend:1.0.0
        envFrom:
        - configMapRef:
            name: backend
